import random

def build_case(players, location, inside_joke='', mode='murder'):
    names=[p['name'] for p in players];culprit=random.choice(names);place=location or 'the living room';joke=' '.join((inside_joke or '').split());innocent=[n for n in names if n!=culprit];decoy=innocent[0] if innocent else names[0];witness=innocent[-1] if innocent else names[0]
    victim='Alex Rosen' if mode=='murder' else ('the Midnight Diamond' if mode=='heist' else 'the leaked file')
    variants=[
      {'title':f'The Eight Seconds at {place}','opening':f'11:47 PM. The lights go out at {place}. Eight seconds later they return. {{event}} The back door is open. A glass is broken. Nobody has entered or left.','false':'the open back door','e1':('The Back Door','A photo timestamped 11:43 PM shows the back door was already open four minutes before the blackout.'),'e2':('The Eight-Second Gap',f'A device log proves someone moved through {place} during the eight-second blackout.'),'missed':'The open door looked important because it was meant to look important.'},
      {'title':f'The Silent Minute at {place}','opening':f'12:16 AM. Music suddenly cuts out at {place}. For one minute nobody can hear what is happening in the next room. When the sound returns, {{event}} A chair is overturned and a phone is missing.','false':'the missing phone','e1':('The Missing Phone','A synced cloud log shows the phone stopped transmitting before the music cut out, so it cannot explain what happened during the silent minute.'),'e2':('The Sound Log','An audio-system log shows one person muted the speakers manually from inside the room.'),'missed':'The missing phone was memorable, but the silence itself was the real mechanism.'},
      {'title':f'The Locked Door at {place}','opening':f'10:32 PM. A door at {place} is found locked from the inside. Thirty seconds later it opens. {{event}} A wet footprint leads away from the scene, but the floor outside is completely dry.','false':'the wet footprint','e1':('The Wet Footprint','The footprint contains cleaning solution from inside the room, not rainwater from outside.'),'e2':('The Lock Record','The smart-lock history proves the door was unlocked remotely seconds before it opened.'),'missed':'The footprint suggested an outsider, but it could only have been made inside.'}
    ]
    v=random.choice(variants);event=(f'{victim} is found beside the table.' if mode=='murder' else f'{victim} is gone.');opening=v['opening'].format(event=event)
    evidence=[{'id':'primary','round':2,'title':v['e1'][0],'text':v['e1'][1]+f' This weakens the obvious theory against {decoy}.'},{'id':'timeline','round':3,'title':v['e2'][0],'text':v['e2'][1]+' One earlier timeline can no longer be true.'}]
    if joke:evidence.insert(1,{'id':'personal','round':2,'title':'The Personal Reference','text':f'A private draft refers to a memory only this group should recognize: “{joke}”. Someone used a real group detail to make the scene feel believable.'})
    roles={}
    for n in names:
      if n==culprit:roles[n]={'role':'The Culprit','secret':f'PUBLIC ALIBI: you were away from {place} when the key moment happened. TRUTH: you caused what happened and deliberately planted {v["false"]} as a false lead.','objective':f'Keep the same timeline every time. Make {decoy} look more suspicious without accusing them too aggressively.','knows':[f'{v["false"].capitalize()} is staged.']}
      elif n==witness:roles[n]={'role':'The Witness','secret':f'PUBLIC ALIBI: you were looking for your phone away from {place}. TRUTH: you briefly stepped into the hallway and saw {culprit} closer to the scene than they claim.','objective':'Help the group without revealing your harmless lie until you absolutely need to.','knows':[f'{culprit} was closer to the scene than they may admit.']}
      else:roles[n]={'role':'The Secret Keeper','secret':f'PUBLIC ALIBI: you were occupied away from {place}. TRUTH: {victim} privately warned you that someone in the group was preparing a distraction.','objective':'Identify the planted clue while keeping the private warning secret for as long as you can.','knows':['The most obvious clue may have been staged on purpose.']}
    rounds=[
      {'number':1,'name':'THE ALIBIS','public':opening,'gm':'I will call on each player in order. Give one short alibi only. Listen carefully: later evidence will test these exact stories.','turns':[{'player':n,'prompt':f'{n}, give your alibi in ONE sentence. Say exactly where you were at the key moment. Do not reveal your private secret.'} for n in names],'finish':'Every alibi is now locked in. Open the first evidence.'},
      {'number':2,'name':'THE EVIDENCE','public':'The first evidence undermines the obvious explanation.','gm':'Read every evidence card aloud. Then each player must challenge one specific detail in someone else’s alibi.','turns':[{'player':n,'prompt':f'{n}, choose one other player. Name ONE exact detail in their alibi that now feels wrong or incomplete.'} for n in names],'finish':'Everyone has challenged a story. Open the contradiction.'},
      {'number':3,'name':'THE CONTRADICTION','public':'A technical record creates a hard contradiction. At least one timeline cannot be fully true.','gm':'No long speeches. Each player gets one defense. You may reveal part of your private information if that is the only way to survive suspicion.','turns':[{'player':n,'prompt':f'{n}, defend ONE exact time, place, or action from your story. If necessary, reveal one piece of private information.'} for n in names],'finish':'The stories are on the table. Move to the final accusation.'},
      {'number':4,'name':'THE ACCUSATION','public':'The investigation is over. Build your final theory before the truth is revealed.','gm':'Everyone gets one final sentence. After that, vote privately on your own screen.','turns':[{'player':n,'prompt':f'{n}, say WHO you suspect and WHICH single clue convinced you.'} for n in names],'finish':'Final statements are complete. Everyone must now vote privately.'},
    ]
    reveal={'headline':f'{culprit} was the culprit.','timeline':[f'Before the key moment, {v["false"]} was prepared as a distraction.','At the critical moment, the public story and the technical evidence split apart.',f'{culprit} acted while relying on the false lead to pull attention elsewhere.','The contradiction exposed the setup.'],'missed_clue':v['missed']}
    return {'title':v['title'],'victim':victim,'culprit':culprit,'opening':opening,'roles':roles,'evidence':evidence,'rounds':rounds,'reveal':reveal,'variant':v['title']}

def public_round(case, number):
    r=case['rounds'][number-1];ev=[e for e in case['evidence'] if e['round']==number]
    return {'number':number,'name':r['name'],'public':r['public'],'gm':r.get('gm',''),'turns':r.get('turns',[]),'finish':r.get('finish',''),'evidence':ev}
