"""Durable, atomic image jobs scoped to a game run; never started by state polling."""
import json
import secrets
import time
from concurrent.futures import ThreadPoolExecutor

POOL = ThreadPoolExecutor(max_workers=2, thread_name_prefix='image')


def init_jobs(c):
    c.execute('''CREATE TABLE IF NOT EXISTS image_jobs(
        game_id BIGINT, image_run INTEGER, round_no INTEGER, job_id TEXT,
        status TEXT, payload TEXT, created DOUBLE PRECISION, deadline DOUBLE PRECISION,
        error TEXT DEFAULT '', UNIQUE(game_id,image_run,round_no))''')


def expire_jobs(c, gid, run):
    # Interrupted calls have unknown billing outcomes: fail closed, do not regenerate.
    c.execute("UPDATE image_jobs SET status='failed',payload='',error='interrupted_or_timeout' "
              "WHERE game_id=? AND image_run=? AND status IN ('queued','running') AND deadline<?",
              (gid, run, time.time()))


def status(c, gid, run, rn):
    expire_jobs(c, gid, run)
    row = c.execute('SELECT status FROM image_jobs WHERE game_id=? AND image_run=? AND round_no=?',
                    (gid, run, rn)).fetchone()
    return row['status'] if row else 'idle'


def queue(cn, g, rn, payload, generate):
    gid, run = g['id'], int(g['image_run'])
    job_id = secrets.token_hex(12)
    with cn() as c:
        # Serialize with replay/start/reset on the game row in both DB backends.
        c.execute('UPDATE games SET image_run=image_run WHERE id=?', (gid,))
        current = c.execute('SELECT image_run FROM games WHERE id=?', (gid,)).fetchone()
        if not current or int(current['image_run']) != run:
            return 'stale'
        if c.execute('SELECT 1 FROM hero_scenes WHERE game_id=? AND round_no=?', (gid, rn)).fetchone():
            return 'ready'
        cur = c.execute('''INSERT INTO image_jobs(game_id,image_run,round_no,job_id,status,payload,created,deadline)
            VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(game_id,image_run,round_no) DO NOTHING''',
            (gid, run, rn, job_id, 'queued', json.dumps(payload, ensure_ascii=False), time.time(), time.time()+600))
        claimed = cur.rowcount == 1
        current_status = status(c, gid, run, rn)
    if claimed:
        POOL.submit(work, cn, gid, run, rn, job_id, generate)
    return current_status


def work(cn, gid, run, rn, job_id, generate):
    args = (gid, run, rn, job_id)
    try:
        with cn() as c:
            c.execute('UPDATE games SET image_run=image_run WHERE id=?', (gid,))
            g = c.execute('SELECT image_run FROM games WHERE id=?', (gid,)).fetchone()
            if not g or int(g['image_run']) != run:
                return
            cur = c.execute("UPDATE image_jobs SET status='running',deadline=? WHERE game_id=? AND image_run=? "
                            "AND round_no=? AND job_id=? AND status='queued' AND deadline>?",
                            (time.time()+330, *args, time.time()))
            if cur.rowcount != 1:
                return
            row = c.execute('SELECT payload FROM image_jobs WHERE game_id=? AND image_run=? AND round_no=? AND job_id=?', args).fetchone()
        payload = json.loads(row['payload'])
        print(json.dumps({'event': 'image_job_start', 'game_id': gid, 'run': run, 'round': rn, 'job_id': job_id}), flush=True)
        art = generate(**payload)
        if not art:
            raise ValueError('generation_failed')
        # Retry storage only, retaining generated bytes; never regenerate after a DB error.
        for attempt in range(3):
            try:
                with cn() as c:
                    c.execute('UPDATE games SET image_run=image_run WHERE id=?', (gid,))
                    g = c.execute('SELECT image_run FROM games WHERE id=?', (gid,)).fetchone()
                    if not g or int(g['image_run']) != run:
                        return
                    cur = c.execute("UPDATE image_jobs SET status='ready',payload='' WHERE game_id=? AND image_run=? "
                                    "AND round_no=? AND job_id=? AND status='running'", args)
                    if cur.rowcount != 1:
                        return
                    c.execute('INSERT INTO hero_scenes(game_id,round_no,image_data,created) VALUES(?,?,?,?) '
                              'ON CONFLICT(game_id,round_no) DO NOTHING', (gid, rn, art, job_id))
                print(json.dumps({'event': 'image_job_saved', 'game_id': gid, 'run': run, 'round': rn, 'job_id': job_id}), flush=True)
                return
            except Exception:
                if attempt == 2:
                    raise
                time.sleep(0.2 * (attempt+1))
    except Exception as exc:
        print(json.dumps({'event': 'image_job_failed', 'game_id': gid, 'run': run, 'round': rn,
                          'job_id': job_id, 'type': type(exc).__name__}), flush=True)
        try:
            with cn() as c:
                c.execute("UPDATE image_jobs SET status='failed',payload='',error=? WHERE game_id=? AND image_run=? "
                          "AND round_no=? AND job_id=? AND status IN ('queued','running')", (type(exc).__name__, *args))
        except Exception:
            pass  # Deadline expiry still moves this job to the fallback state.


def recover(cn, generate):
    # Only queued jobs are safe to resume; running jobs might have reached the provider.
    with cn() as c:
        rows = c.execute("SELECT j.game_id,j.image_run,j.round_no,j.job_id FROM image_jobs j JOIN games g ON "
                         "g.id=j.game_id AND g.image_run=j.image_run WHERE j.status='queued' AND j.deadline>?",
                         (time.time(),)).fetchall()
    for row in rows:
        POOL.submit(work, cn, row['game_id'], row['image_run'], row['round_no'], row['job_id'], generate)
