// Actual production image gate: no intermediate composite and no early Next.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const page=fs.readFileSync('static/kyc.html','utf8');
assert.match(page,/finalImagePending/);assert.match(page,/finalWaitTitle/);
const source=page.slice(page.indexOf('const visualCache='),page.indexOf('async function makeFinalHero('));
const elements={},images={},timers=[],frames=[];
function element(id){return elements[id]||={dataset:{},style:{},classList:{set:new Set(),add(x){this.set.add(x)},remove(x){this.set.delete(x)},toggle(x,v){v?this.add(x):this.remove(x)}}}}
class Image {set src(url){this.url=url;images[url]=this}get src(){return this.url}}
const sandbox={copy:{image_loading:'Loading…',image_failed:'Failed',image_continue:'Continue without image',next:'Next',play_again:'Play again'},Image,performance:{now:()=>100},requestAnimationFrame:fn=>frames.push(fn),setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout(){},imageView:'run1',heroAsked:-1,$:element,makeHero(){},makeFinalHero(){}};
vm.createContext(sandbox);vm.runInContext(source,sandbox);
function paint(){while(frames.length)frames.shift()()}
const d={code:'TEST',image_run:1,round:0,total:12,hero_eligible:true,ai_images_ready:true,instant_visual:'/instant',subject:{photo_url:'/photo.jpg'},hero_status:'running'};
sandbox.renderRoundImage(d);
assert.equal(element('#next').disabled,true);
assert.ok(element('#visualStage').classList.set.has('is-loading'));
assert.match(element('#heroStatus').innerHTML,/waitDots/);
assert.equal(element('#heroImg').style.display,'none');
assert.equal(images['/instant'],undefined,'never display/download composite through renderer');
sandbox.renderRoundImage({...d,hero:'/full',hero_status:'ready'});
assert.equal(element('#next').disabled,true,'server ready does not unlock before download');
images['/full'].onload();
assert.equal(element('#next').disabled,true,'wait for actual paint');
paint();
assert.equal(element('#next').disabled,false);
assert.equal(element('#heroImg').src,'/full');
assert.ok(element('#heroStatus').classList.set.has('hidden'));
sandbox.imageView='run2';sandbox.renderRoundImage({...d,round:1,hero_status:'failed'});
assert.equal(element('#next').disabled,false);
assert.equal(element('#next').textContent,'Continue without image');
assert.equal(element('#heroStatus').textContent,'Failed');
sandbox.imageView='run3';sandbox.renderRoundImage({...d,round:2,hero:'/broken',hero_status:'ready'});
images['/broken'].onerror();
assert.equal(element('#next').disabled,false);
assert.equal(element('#heroImg').style.display,'none');
sandbox.imageView='run4';sandbox.renderRoundImage({...d,round:3});
assert.equal(element('#next').disabled,true);
timers.at(-1)();assert.equal(element('#next').disabled,false,'bounded wait');
sandbox.imageView='run5';sandbox.renderRoundImage({...d,round:4,hero:'/late'});
const late=images['/late'].onload;
sandbox.imageView='run6';sandbox.renderRoundImage({...d,round:5,hero_eligible:false});
late();paint();assert.equal(element('#heroImg').style.display,'none');
assert.equal(element('#next').disabled,false,'no photo never blocks');
sandbox.imageView='final';
sandbox.renderFinalImage({...d,final_image_eligible:true,final_hero_status:'running'});
assert.equal(element('#replayBtn').disabled,true);
assert.match(element('#finalHeroStatus').innerHTML,/winner image|תמונת הניצחון/);
sandbox.renderFinalImage({...d,final_image_eligible:true,final_hero_status:'ready',final_hero:'/final'});
images['/final'].onload();paint();
assert.equal(element('#replayBtn').disabled,false);
assert.equal(element('#finalHeroImg').src,'/final');
console.log('FINAL_AI_ONLY_DOWNLOAD_PAINT_GATE_FAILURE_TIMEOUT_STALE_FINAL_OK');
